import React, { useState, useRef } from 'react';
import { GoogleGenAI } from "@google/genai";
import ReactMarkdown from 'react-markdown';
import { Sparkles, Loader2, AlertTriangle, Copy, FileDown, Check } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface SummaryProps {
  yaml: string;
  currentSummary: string | null;
  onSummaryUpdate: (summary: string) => void;
}

const Summary: React.FC<SummaryProps> = ({ yaml, currentSummary, onSummaryUpdate }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied'>('idle');
  const [pdfGenerating, setPdfGenerating] = useState(false);
  
  const contentRef = useRef<HTMLDivElement>(null);

  const generateSummary = async () => {
    if (!process.env.API_KEY) {
      setError("API Key not configured in environment.");
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const model = 'gemini-2.5-flash';
      
      const prompt = `
        Act as a DevOps expert specializing in Harvester (built on SLE Micro and Elemental) and Cloud-Init. 
        Analyze the following Multi-Document YAML configuration (contains one or more CloudInit CRDs). 
        
        Important Context:
        - The underlying OS is SLE Micro + Elemental. Do NOT use the term "Harvester OS".
        - The 'multipathd' package is installed by default but the service is DISABLED. If the config involves storage/multipath, verify if the service is enabled.
        
        1. Summarize the purpose of EACH configuration document present in the YAML.
        2. Identify potential security risks (e.g., hardcoded passwords, overly permissive files) across all configs.
        3. Analyze for "gotchas" and stability issues, such as:
           - Using unstable device names (e.g., /dev/sda) in fstab/mounts (suggest UUIDs/LABELs).
           - Network race conditions (scripts running before network is up).
           - Service ordering (restarting services before config is in place).
           - Filesystem immutability (writing to read-only paths in Boot phase).
           - Multipath: If relevant, remind user to 'systemctl enable --now multipathd' and link to documentation.
        4. Highlight any syntax oddities or logical errors.
        5. Provide links to official Harvester (https://docs.harvesterhci.io/latest/) documentation for best practices.
        6. Output in clean Markdown format. Use headers, bullet points, and code blocks.

        YAML Configuration:
        \`\`\`yaml
        ${yaml}
        \`\`\`
      `;

      const result = await ai.models.generateContent({
        model,
        contents: prompt,
      });

      if (result.text) {
        onSummaryUpdate(result.text);
      }
    } catch (err: any) {
      setError(err.message || "Failed to generate summary");
    } finally {
      setLoading(false);
    }
  };

  const handleCopyMarkdown = () => {
    if (currentSummary) {
      navigator.clipboard.writeText(currentSummary);
      setCopyStatus('copied');
      setTimeout(() => setCopyStatus('idle'), 2000);
    }
  };

  const handleExportPDF = () => {
    if (!currentSummary) return;
    setPdfGenerating(true);

    try {
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'pt',
            format: 'a4'
        });

        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        const margin = 40;
        const maxLineWidth = pageWidth - (margin * 2);
        let yCursor = 40;

        const addNewPage = () => {
            pdf.addPage();
            yCursor = margin;
        };

        const checkPageBreak = (heightNeeded: number) => {
            if (yCursor + heightNeeded > pageHeight - margin) {
                addNewPage();
            }
        };

        // --- PDF Header ---
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(18);
        pdf.setTextColor(12, 50, 44); // Dark Harvester Green
        pdf.text("AI Configuration Analysis", margin, yCursor);
        yCursor += 20;

        pdf.setFont("helvetica", "italic");
        pdf.setFontSize(9);
        pdf.setTextColor(80, 80, 80); // Gray
        pdf.text("Generated by Harvester CloudInit Architect", margin, yCursor);
        yCursor += 12;
        pdf.text("https://doccaz.github.io/harvester-cloud-init/", margin, yCursor);
        yCursor += 12;
        pdf.setTextColor(120, 120, 120);
        pdf.text(new Date().toLocaleString(), margin, yCursor);
        yCursor += 25;

        // --- Render Markdown Summary as Native Text ---
        // Simple Markdown parser for PDF text rendering
        const lines = currentSummary.split('\n');
        
        lines.forEach((line) => {
            let fontSize = 10;
            let fontStyle = 'normal';
            let indent = 0;
            let text = line;
            let spacing = 14; 

            // Basic Markdown Header detection
            if (line.startsWith('### ')) {
                fontSize = 12;
                fontStyle = 'bold';
                text = line.replace('### ', '');
                spacing = 18;
                yCursor += 6; 
            } else if (line.startsWith('## ')) {
                fontSize = 14;
                fontStyle = 'bold';
                text = line.replace('## ', '');
                spacing = 22;
                yCursor += 10;
            } else if (line.startsWith('# ')) {
                fontSize = 16;
                fontStyle = 'bold';
                text = line.replace('# ', '');
                spacing = 26;
                yCursor += 12;
            } 
            // Lists
            else if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
                indent = 12;
                text = '• ' + line.trim().substring(2);
            }
            else if (/^\d+\.\s/.test(line.trim())) {
                indent = 12;
                // Keep numbered list as is
            }

            // Remove bold/italic markers for cleaner plain text PDF
            text = text.replace(/\*\*/g, '').replace(/__/g, '').replace(/`/g, '');

            pdf.setFont("helvetica", fontStyle);
            pdf.setFontSize(fontSize);
            pdf.setTextColor(30, 30, 30);

            // Calculate text wrapping
            const wrappedLines = pdf.splitTextToSize(text, maxLineWidth - indent);
            const blockHeight = wrappedLines.length * spacing;

            checkPageBreak(blockHeight);

            pdf.text(wrappedLines, margin + indent, yCursor);
            yCursor += blockHeight;

            // Add paragraph spacing for plain text
            if (!line.startsWith('#') && !line.startsWith('-') && wrappedLines.length > 0) {
                 yCursor += 4; 
            }
        });

        yCursor += 30;

        // --- YAML Section ---
        checkPageBreak(50);
        
        // Separator
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, yCursor - 15, pageWidth - margin, yCursor - 15);

        pdf.setFont("courier", "bold");
        pdf.setFontSize(14);
        pdf.setTextColor(33, 33, 33);
        pdf.text("Analyzed YAML Configuration", margin, yCursor);
        yCursor += 20;

        pdf.setFont("courier", "normal");
        pdf.setFontSize(8); 
        pdf.setTextColor(50, 50, 50);

        // Render YAML code block
        const yamlLines = pdf.splitTextToSize(yaml, maxLineWidth);
        const yamlLineHeight = 10;

        for (let i = 0; i < yamlLines.length; i++) {
             checkPageBreak(yamlLineHeight);
             pdf.text(yamlLines[i], margin, yCursor);
             yCursor += yamlLineHeight;
        }

        pdf.save('harvester-config-analysis.pdf');

    } catch (e) {
        console.error("PDF Export failed", e);
        alert("Failed to generate PDF. Check console.");
    } finally {
        setPdfGenerating(false);
    }
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold text-gray-100 flex items-center">
          <Sparkles className="text-yellow-400 mr-2" size={24} />
          AI Configuration Analysis
        </h2>
        <button
          onClick={generateSummary}
          disabled={loading}
          className={`px-4 py-2 rounded font-medium flex items-center transition-colors ${
            loading 
              ? 'bg-gray-700 text-gray-400 cursor-not-allowed' 
              : 'bg-purple-600 hover:bg-purple-500 text-white'
          }`}
        >
          {loading ? <Loader2 className="animate-spin mr-2" size={18} /> : <Sparkles className="mr-2" size={18} />}
          {loading ? 'Analyzing...' : currentSummary ? 'Regenerate Analysis' : 'Generate Analysis'}
        </button>
      </div>

      {error && (
        <div className="bg-red-900/50 border border-red-700 text-red-200 p-4 rounded flex items-start">
          <AlertTriangle className="mr-3 flex-shrink-0" />
          <p>{error}</p>
        </div>
      )}

      {currentSummary && (
        <div className="bg-gray-800 rounded-lg border border-gray-700 shadow-xl overflow-hidden">
            <div className="bg-gray-900/50 border-b border-gray-700 px-4 py-2 flex justify-end gap-2">
                <button 
                    onClick={handleCopyMarkdown}
                    className="flex items-center px-3 py-1.5 text-xs font-medium text-gray-300 hover:text-white hover:bg-gray-700 rounded transition-colors"
                >
                    {copyStatus === 'copied' ? <Check size={14} className="mr-1.5 text-emerald-400" /> : <Copy size={14} className="mr-1.5" />}
                    {copyStatus === 'copied' ? 'Copied' : 'Copy Markdown'}
                </button>
                <button 
                    onClick={handleExportPDF}
                    disabled={pdfGenerating}
                    className="flex items-center px-3 py-1.5 text-xs font-medium text-gray-300 hover:text-white hover:bg-gray-700 rounded transition-colors disabled:opacity-50"
                >
                    {pdfGenerating ? <Loader2 size={14} className="mr-1.5 animate-spin" /> : <FileDown size={14} className="mr-1.5" />}
                    Export PDF
                </button>
            </div>
            
            <div ref={contentRef} className="p-8 bg-gray-800 text-gray-100">
                <ReactMarkdown 
                    className="prose prose-invert max-w-none 
                    prose-headings:text-emerald-400 prose-headings:font-bold 
                    prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg
                    prose-a:text-blue-400 hover:prose-a:text-blue-300
                    prose-strong:text-white
                    prose-code:text-yellow-200 prose-code:font-medium prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-code:border prose-code:border-gray-600 prose-code:bg-transparent prose-code:before:content-none prose-code:after:content-none
                    prose-pre:bg-gray-900 prose-pre:border prose-pre:border-gray-700 prose-pre:shadow-inner
                    prose-li:text-gray-300
                    prose-p:text-gray-300 prose-p:leading-relaxed"
                >
                    {currentSummary}
                </ReactMarkdown>
            </div>
        </div>
      )}

      {!currentSummary && !loading && !error && (
        <div className="text-center py-24 text-gray-500 border-2 border-dashed border-gray-800 rounded-lg bg-gray-900/30">
          <Sparkles size={48} className="mx-auto mb-4 text-gray-700" />
          <h3 className="text-lg font-medium text-gray-400 mb-2">Ready to Analyze</h3>
          <p className="max-w-md mx-auto">Click "Generate Analysis" to have Gemini review your Cloud-Init configuration for security risks and logical errors.</p>
        </div>
      )}
    </div>
  );
};

export default Summary;